### ISSUE TITLE
[error]  Cannot read property 'feed' of undefined

### ISSUE THREAD

**Issue by loveLibra** [hexojs/hexo-generator-feed#12]
After I install  hexo-generator-feed and add configures in _config.yml...I run the 'hexo server',It throw the error "[error] 23:16:12.492 TypeError: Cannot read property 'feed' of undefined"...the error show: the config is undefined in Line16 of lib/generator.js.I cannot find any solutions.May I ask u tell me why,thks
the config in _config.yml is append after,just like some aritcals show:

-------------------------------
plugins:
- hexo-generator-feed

feed:
  type: atom
  path: atom.xml
  limit: 20

-----------------------------

**Comment by rhamdeew** [comment]
A similar error

**Comment by weyou** [comment]
the same error

**Comment by tommy351** [comment]
What version did you install?

**Comment by weyou** [comment]
hexo 2.8.3. It works after upgrading to 3.0.0.
2015年3月11日 PM7:15于 "Tommy Chen" <notifications@github.com>写道：

**Comment by leejanfin** [comment]
the same error

**Comment by jlovedragon** [comment]
the same error

**Comment by xring** [comment]
same error 

hexo 2.8.3

**Comment by xring** [comment]
edit package.json

change "hexo-generator-feed": "^1.0.2" to "hexo-generator-feed": "^0.2.0"

and it works.

**Comment by Xuanwo** [comment]
look after the wiki & update hexo to 3.x
