### ISSUE TITLE
生成不同category的rss

### ISSUE THREAD

**Issue by qzi** [hexojs/hexo-generator-feed#127]
如果生成不同category的rss更好，那样就可以写几个类别给不同的人订阅，并不是所有的人都对所有类别感兴趣

**Comment by bestony** [comment]
很好的想法，不过似乎可以通过插件的方式来实现

**Comment by qzi** [comment]
> 很好的想法，不过似乎可以通过插件的方式来实现

刚需

**Comment by qzi** [comment]
> 很好的想法，不过似乎可以通过插件的方式来实现

想了解你想的方案

**Comment by SukkaW** [comment]
@qzi

**Comment by qzi** [comment]
> @qzi
> 
> https://github.com/hexojs/hexo-generator-feed/blob/76c220b8f43caa78db199f7fd08cfceec78ecc78/lib/generator.js#L28
> 
> As you can see, the plugin read post list from `locals`.
> 
> Base on this, you can write your own RSS generator then.

哇，厉害，sukka同时在维护很多插件的感觉，我不太懂nodejs，可能得学习一下研究代码才能构建一个扩展，回头有空试试

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #3
I'm closing this issue. Please join the discussion there :)
