### ISSUE TITLE
Missing articles in atom

### ISSUE THREAD

**Issue by vulgur** [hexojs/hexo-generator-feed#138]
The generated atom don't contains all the articles of year 2020.

**Comment by tomap** [comment]
There is a settings to limit the number of posts visible in the atom feed. The default value is 20. Maybe you hit that limit. 
Try increasing this value in the settings: 
https://github.com/hexojs/hexo-generator-feed#options

```yml
feed:
  limit: 90
```

**Comment by vulgur** [comment]
@tomap Indeed, I hit the limit. Thanks for your help, but why not make the limit for the latest articles ?

**Comment by tomap** [comment]
This should be the case (order by date, and take the last ones). You might have a date issue on your articles, which would explain why your 2020 article is not visible?
There is a settings for that also, but the default value should be the right one (see the link above)

**Comment by vulgur** [comment]
@tomap I've raised the limit to 90, but latest ones are still not included. 
Does the date matter in file name or front-matter?
Filenames of my articles are below.

<img width="387" alt="截屏2020-05-02 22 03 02" src="https://user-images.githubusercontent.com/3339536/80866509-aac78280-8cc1-11ea-9f59-8bc96c7a99ab.png">

**Comment by tomap** [comment]
Maybe there is something wrong with your article header/front matter?
Can you send them?

**Comment by vulgur** [comment]
I found the reason. 
There is a `draft: true` in my header.
