### ISSUE TITLE
How can I add images to the feed?

### ISSUE THREAD

**Issue by ozkxr** [hexojs/hexo-generator-feed#14]
My posts have images but when I generate the .xml file it doesn't show any image. This package supports this feature?

**Comment by ozkxr** [comment]
Sorry. The RSS standard doesn't provide an option to add an image per entry.

**Comment by oncletom** [comment]
Even with the `<enclosure>` element? https://cyber.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt

Other hexo plugins use the `image` metadata to populate `twitter:image` and `og:image`. It could make sense to reflect this behaviour by forwaring the `image` as the default `enclosure` element.

By configuration, another front matter value could be picked up too.
