### ISSUE TITLE
Option to disable feed generation when using hexo server

### ISSUE THREAD

**Issue by Buzut** [hexojs/hexo-generator-feed#140]
As when using Hexo server we often look for speed over everything, it could be a really nice option to be able to disable the feed generation when using the local webserver (watch mode).

**Comment by tomap** [comment]
You should be able to do that with the hexo command line:

Your current command:

```sh
hexo s -o
```
Your new command:

```sh
hexo --config _config.yml,_local.yml s -o
```

See https://hexo.io/docs/commands.html#Customize-config-file-path

And the content of _local.yml:

```yml
feed:
  enable: false

```

This would disable the feed plugin only locally 👍 

Except there is currently no "enable/disable" option. I'll code it and make a MR ASAP :)

**Comment by Buzut** [comment]
That's sooo neat. Thank you very much 👍
