### ISSUE TITLE
Need absolute URI for rel="self" link

### ISSUE THREAD

**Issue by nsamarak** [hexojs/hexo-generator-feed#157]
Per the W3C guidelines (https://validator.w3.org/feed/docs/warning/RelativeSelf.html), rel="self" links need to be absolute URIs, not relative. Services such as Google News and Apple News require the rel="self" link to match the W3C guidelines in order for them to consume your blog content.

I'm on hexo-generator-feed 2.2.0 and the rel="self" link is relative, so I was going to submit a pull request. However, the latest code in github (see below) appears to generate an absolute URI. Is that correct?

https://github.com/hexojs/hexo-generator-feed/blob/60fe0b54b25e9764ec4b1924095eb9ababbfc577/lib/generator.js#L52

**Comment by SukkaW** [comment]
> I'm on hexo-generator-feed 2.2.0 and the rel="self" link is relative, so I was going to submit a pull request. However, the latest code in github (see below) appears to generate an absolute URI. Is that correct?

The latest version of `hexo-generator-feed` is 3.0.0. Try update first?
