### ISSUE TITLE
How to access theme variable within a given custom_atom.xml file

### ISSUE THREAD

**Issue by Ramesh-X** [hexojs/hexo-generator-feed#159]
I can't access many of the hexo global variables, including the theme configuration as mentioned [here](https://hexo.io/docs/variables.html) from within a given `custom_atom.xml` file as a template. 

The only variables that can be accessed are `posts` and `config`. 

Is there any way to access the other global variables as well??

**Comment by jiangtj** [comment]
https://github.com/hexojs/hexo-generator-feed/blob/93a0124b7029b9de77f7d85a9e9e14c36da3d213/lib/generator.js#L54-L60

Yes, template can only accept some variables. But the plugin is independent of the theme, so I don't think it is necessary to add the theme variable. If you have anything to configure, maybe you can move them to `_config.yml`

**Comment by Ramesh-X** [comment]
That's how I do it currently. 
Thanks for the reply.

As it is not necessary to have a theme for a `hexo` project, I think this will not be implemented in the future also. Therefore I will close the issue.
