### ISSUE TITLE
hexo如何让RSS全文输出？

### ISSUE THREAD

**Issue by woheme** [hexojs/hexo-generator-feed#16]
你好，我在文章中加了标签后，RSS输出只有摘要，怎样设置可以全文输出？(PS：我不想去掉摘要标签)

**Comment by Xuanwo** [comment]
http://wohe.me/atom.xml

根据我的观察，Hexo生成的atom.xml同时具有摘要和全部内容啊

**Comment by woheme** [comment]
额。。我看错了么，但是直接RSS同步到EverNote只有摘要部分
