### ISSUE TITLE
3.0.0版本本地测试有乱码，但是部署到网站上显示正常

### ISSUE THREAD

**Issue by lizilong1993** [hexojs/hexo-generator-feed#197]
> > 3.0.0版本亲测有乱码，所有中文都是乱码。
> 
> 是的，我的如下 ![image](https://user-images.githubusercontent.com/25758122/211022928-c0eca6ee-17d9-4919-be91-39e24bab83cc.png) 版本如下
> 
> * hexo-generator-feed: ^3.0.0
> * hexo: 6.3.0
> * hexo-cli: 4.3.0
> * Windows 11

我发现本地预览乱码，但是远程却没问题，不知道是什么原因导致的。
![image](https://user-images.githubusercontent.com/25758122/211132630-fe6da5e5-f7ca-404b-8710-80d5801d3e28.png)

_Originally posted by @lizilong1993 in https://github.com/hexojs/hexo-generator-feed/issues/39#issuecomment-1374383388_

**Comment by adoyle-h** [comment]
请问这个问题是什么解决的？

**Comment by lizilong1993** [comment]
> 请问这个问题是什么解决的？

我觉得远程显示正常我能接受

**Comment by stevenjoezhang** [comment]
可能服务器 header 少了 encoding，浏览器没认出 UTF-8，当作 GBK 解码了。实际上没问题。
