### ISSUE TITLE
Convert image absolute/relative src link with full URL

### ISSUE THREAD

**Issue by atika** [hexojs/hexo-generator-feed#25]
Is it possible to convert image src link without hostname with the full URL? The image doesn't display on aggregator.

I have an image like this : `<img src="/root/to/my/image.jpg" />` and I want to convert with `<img src="https://my.blog.tld/root/to/my/image.jpg" />`

I have temporarily modified the script to add the hostname...

``` javascript
ejs.filters.cdata = function(str){
  str = str.replace(/src="+\//g, 'src="https://my.blog.tld/');
  return str ? '<![CDATA[' + str + ']]>' : '';
};
```

Thanks,

**Comment by Xuanwo** [comment]
May be we can add it as an option.

**Comment by leesei** [comment]
@atika Are you intending to replace all links within CDATA?
It could be a boolean option `abs_link`  that replace `'src="/'` with `'src="url.resolve(config.url, config.root)'`.
Please verify and submit PR.

**Comment by atika** [comment]
@leesei I think that in RSS links can't be relative, if you have not an image with an absolute link it doesn't works on aggregator.

I tried to modify the script but I don't know the best way to achieve this, it is a little complicate for me.

```js
// generator.js
var url = require('url');

ejs.filters.absoluteUrls = function(content, blog_url){
  str = content.replace(/(src|href)="(\S+)"/g, "$1=\""+url.resolve(blog_url, "$2")+"\"");
  return str;
};
```
```js
// atom.ejs
<content type="html"><%-: post.content | absoluteUrls:url | cdata %></content>
```
The problem here is that outside the replace function, `url.resolve` works great, but inside as this it append the two variables instead of resolving them:
```html
<p>
<img src="https://domain.tld/../images/relativeimages.png" alt="TEST IMAGE RELATIVE"><br>
<a href="https://domain.tld/http://monsite.com/toto.html" target="_blank" rel="external">TEST EXTERNAL LINK</a><br>
<a href="https://domain.tld/../2009/monsite.html">TEST EXTERNAL LINK</a></p>
```

**Comment by bacinger** [comment]
@atika did you maybe solve this problem in the meantime?

**Comment by atika** [comment]
@bacinger Not really, I tried but in the meantime this repo has been updated to use another system (Nunjucks). I left fell. You can try but ...
- Clone this fork anywhere: https://github.com/atika/hexo-generator-feed
- A this to your *package.json*: `"hexo-generator-feed": "file:///Users/USERNAME/PATH/TO/hexo-generator-feed",`
- `npm update`

**Comment by leesei** [comment]
@atika I agree that links should be absolute by default.

BTW, you can use GitHub repo directly in `package.json`.
http://stackoverflow.com/a/19351036/665507

**Comment by oncletom** [comment]
Maybe exposing a filter could help?

```js
hexo.extend.filter.register('plugin_generator_feed.item', post => {
  post.content = post.content.replace(...);

  return post;
});
```

AMA @atika you should create this filter at your blog level because you want to benefit from this for other social cards such as Open Graph images and Twitter Cards images metadata. The RSS feed would benefit de facto from the native filter.

In any case, I would be interested by exposing such a filter in order to move a cover image to the article content – at the moment this is something I do via article layouts + front-matter metadata.

**Comment by NetOperatorWibby** [comment]
@atika Your fork works wonderfully, thanks for creating it!

**Comment by jongio** [comment]
@atika - Do you have plans to PR this into upstream?  Jon

**Comment by atika** [comment]
@jongio Not really, my fork is 3 years old, 40 commits behind, and its was just a temporary workaround I found when I waiting a reply for someone who could know the framework better than me. If you prompt this is that it is not yet resolved...

**Comment by nyex** [comment]
I would love to have this available... anyone with enough programming skills interested, maybe?
