### ISSUE TITLE
The generated atom.xml contains Control Characters which prevents the atom.xml from being recognised correctly

### ISSUE THREAD

**Issue by axl411** [hexojs/hexo-generator-feed#35]
I'm using hexo 3.2.0 and hexo-generator-feed 1.1.0.

I get an error opening the generated atom.xml: `error on line 41 at column 428: PCDATA invalid Char value 16`

I find that most characters whose char value is less than 32(decimal) is a Control Character and should not be put in the atom.xml, see [this](https://github.com/neitanod/forceutf8/issues/39) and [this](http://www.robelle.com/smugbook/ascii.html). The most useful info from [here](https://github.com/neitanod/forceutf8/issues/39) is:

>When you put utf-8 encoded strings in a XML document you should remember that not all utf-8 valid > chars are accepted in a XML document http://www.w3.org/TR/REC-xml/#charsets
So you should strip away the unwanted chars, else you’ll have an XML fatal parsing error

So I suppose if those characters can be removed from atom.xml when we generate it, I will no longer get the error.

By the way, [this issue](https://github.com/hexojs/hexo-generator-feed/issues/9) should be caused by the same reason.

**Comment by f213** [comment]
Did you try an unstable version of hexo-generator-feed? I think [this PR](https://github.com/hexojs/hexo-generator-feed/pull/31) should solve your issue.

**Comment by axl411** [comment]
I can see your PR is added on Mar 26, but the latest release of hexo-generator-feed (1.1.0) is on Feb 6, so your code is not in the latest release...

**Comment by axl411** [comment]
Now the new version is released, this issue is confirmed to be resolved.
