### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by JayceCao** [hexojs/hexo-generator-feed#38]
安装hexo-generator-feed的时候回显如下： 
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
hexo-generator-feed@1.1.0 node_modules/hexo-generator-feed
├── object-assign@4.1.0
└── nunjucks@1.3.4 (optimist@0.6.1, chokidar@0.12.6)
之后在_config.yml中配置如下：
plugins:
- hexo-generator-feed
使用hexo -g生成的时候出现错误：
![2016-07-15 12-52-52](https://cloud.githubusercontent.com/assets/17915615/16863998/5a6f82ea-4a1e-11e6-9daf-cd85bce8a2f3.png)
![2016-07-15 12-53-19](https://cloud.githubusercontent.com/assets/17915615/16864016/8d1585d2-4a1e-11e6-9154-50046ebd26e5.png)

hexo version: v3.2.2

**Comment by JayceCao** [comment]
graceful-fs: v4.1.4
minimatch: v3.0.2

**Comment by JayceCao** [comment]
是不是和我用的主题有关

**Comment by Xuanwo** [comment]
停用这个插件还会有错误么？

**Comment by JayceCao** [comment]
不会有

**Comment by Xuanwo** [comment]
去掉_config.yml 文件中的 plugins 部分内容试试

**Comment by JayceCao** [comment]
我只安装了这一个额外插件，去掉plugins之后正常

**Comment by Xuanwo** [comment]
去掉plugins就可以了，现在插件是自动加载的。

**Comment by JayceCao** [comment]
但还是没有rss啊。。。

**Comment by Xuanwo** [comment]
可以参考： https://github.com/Xuanwo/xuanwo.github.io/blob/blog/_config.yml 
进行配置

**Comment by JayceCao** [comment]
搞定了！打扰了！

**Comment by Acris** [comment]
@JayceCao @Xuanwo 你们安装这个插件的时候是直接 `npm install hexo-generator-feed --save` 安装的，还是下载源码自己 `npm install` 安装的？我直接用 `npm install hexo-generator-feed --save` 安装后生成的atom.xml包含很多转义字符，无法正常使用，从源码编译安装的正常，你们的呢？感谢。

**Comment by JayceCao** [comment]
我是直接`npm install hexo-generator-feed --save`。我用的rss阅读器是Chrome的插件`RSS Feed Reader`，如果打开有RSS的网页，比如Github的话会提示你订阅。但是用这个插件，要订阅的话只有打开xml页面才能出现提示。 @Acris @Xuanwo

**Comment by Acris** [comment]
@JayceCao 你Node.js版本是多少呢，我的版本是6.3.0，直接安装的话生成的xml中很多转义字符，你的就没问题，好奇怪。

**Comment by JayceCao** [comment]
我的是4.4.7。你的RSS能正常使用吗 @Acris

**Comment by Acris** [comment]
@JayceCao 直接 `npm install hexo-generator-feed --save` 安装是不行的，但是git clone最新的源码安装是可以的。可能和Node.js版本有关系，希望作者能尽快发布新版本修复这个问题。

**Comment by hkongm** [comment]
支持！需要更新版本了。。。

**Comment by Xuanwo** [comment]
我也只能帮你们 @tommy351 了，我们没有推npm的权限。

**Comment by kudotty** [comment]
Use this forked repository
`npm install cnpolitics/hexo-generator-feed--cnp-radio --save`

It works.

**Comment by tommy351** [comment]
hexo-generator-feed@1.2.0 is published

**Comment by FundiJet** [comment]
@JayceCao 请问如何解决的？

**Comment by JayceCao** [comment]
@FundiJet 去掉plugins就可以了，现在插件是自动加载的。
