### ISSUE TITLE
RSS生成的atom.xml乱码问题

### ISSUE THREAD

**Issue by shliujing** [hexojs/hexo-generator-feed#39]
## Description (描述)

貌似属于编码问题。
我安装了feed插件，配置文件按照`README.md`设置，产生乱码。
版本`"hexo-generator-feed": "^1.1.0",`。
环境：`windows7/10`（mac下测试无误）
### Expected behavior (预期行为)

![](http://7xncbk.com1.z0.glb.clouddn.com/useless/1.png)
### Actual behavior (实际行为)

![](http://7xncbk.com1.z0.glb.clouddn.com/useless/2.png)

**Comment by Acris** [comment]
1.2.0应该可以了，你更新下试试。

**Comment by shliujing** [comment]
我刚update了，还是乱码呢

**Comment by Acris** [comment]
@shliujing 咦 我这边之前和你一样，更新之后就好了，你试试把你博客目录下package.json中的版本号改为1.2.0，再npm install一下看看。

**Comment by shliujing** [comment]
我卸载了又重新安装，还是存在问题。
你是不是还有其他设置呢呀@Acris。我现在的环境是win10，问题如下：
![](http://7xncbk.com1.z0.glb.clouddn.com/16-7-23/21381323.jpg)

**Comment by Acris** [comment]
看样子是编码问题，用IE访问rss正常。你检查一下你的.md文件是不是UTF-8编码。

**Comment by shliujing** [comment]
md和atom.xml文件都是utf-8编码。
还真有趣，IE11下不是乱码，而且显示还挺好看!Chrome下倒是乱码，不知道这个算不算是个Bug，还是个人设置问题。

**Comment by shliujing** [comment]
![](http://7xncbk.com1.z0.glb.clouddn.com/16-7-23/52412594.jpg)

**Comment by AmyFoxFN** [comment]
我也遇到了这个问题，同是utf-8编码的

**Comment by stevenjoezhang** [comment]
最新发布的版本 2.2.0。如果问题仍然存在，请重新打开这个 Issue。

**Comment by tuliren** [comment]
使用 3.0.0 版本，`atom` 类型 feed，输出有乱码。

使用环境是 Mac，确认 markdown 文件都是 UTF-8 编码。好在 `rss2` 类型的 feed 没有问题。

**Comment by kingname** [comment]
3.0.0版本亲测有乱码，所有中文都是乱码。

**Comment by lizilong1993** [comment]
> 3.0.0版本亲测有乱码，所有中文都是乱码。

是的，我的如下
![image](https://user-images.githubusercontent.com/25758122/211022928-c0eca6ee-17d9-4919-be91-39e24bab83cc.png)
版本如下
- hexo-generator-feed: ^3.0.0
- hexo: 6.3.0
- hexo-cli: 4.3.0
- Windows 11

**Comment by lizilong1993** [comment]
> > 3.0.0版本亲测有乱码，所有中文都是乱码。
> 
> 是的，我的如下 ![image](https://user-images.githubusercontent.com/25758122/211022928-c0eca6ee-17d9-4919-be91-39e24bab83cc.png) 版本如下
> 
> * hexo-generator-feed: ^3.0.0
> * hexo: 6.3.0
> * hexo-cli: 4.3.0
> * Windows 11

我发现本地预览乱码，但是远程却没问题，不知道是什么原因导致的。
![image](https://user-images.githubusercontent.com/25758122/211132630-fe6da5e5-f7ca-404b-8710-80d5801d3e28.png)

**Comment by kingname** [comment]
> > > 3.0.0版本亲测有乱码，所有中文都是乱码。
> > 
> > 
> > 是的，我的如下 ![image](https://user-images.githubusercontent.com/25758122/211022928-c0eca6ee-17d9-4919-be91-39e24bab83cc.png) 版本如下
> > 
> > * hexo-generator-feed: ^3.0.0
> > * hexo: 6.3.0
> > * hexo-cli: 4.3.0
> > * Windows 11
> 
> 我发现本地预览乱码，但是远程却没问题，不知道是什么原因导致的。 ![image](https://user-images.githubusercontent.com/25758122/211132630-fe6da5e5-f7ca-404b-8710-80d5801d3e28.png)

我发现在hexo -s弹出的页面上看atom.xml会有乱码，但是部署到远程以后，打开就是正常的。

**Comment by ayakasuki** [comment]
3.0.0同hexo -s会乱码

**Comment by stevenjoezhang** [comment]
这个可能是服务器的问题，服务器返回的HTTP头里面如果缺少字符集的信息，浏览器可能用其它编码打开（而不是UTF-8），就导致乱码了，但其实`atom.xml`文件内容本身是正确的
