### ISSUE TITLE
Bad links in RSS

### ISSUE THREAD

**Issue by arkasha69** [hexojs/hexo-generator-feed#5]
I change root path in _config.yml and all links in RSS feed are broken - there is no root path in post.permalink property.

**Comment by ahaasler** [comment]
Are you setting the url properly according with docs?

> If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'

And I think this issue should be reopened, because it was not fixed (if needs fixing) in #18. It's a side effect of GitHub auto closing if the word fix is before the issue number.

**Comment by ahaasler** [comment]
I just checked this and the post links are well formed in the RSS (also Atom) feed and contain the root path. You must set `url` and `root` in your configuration file properly.
