### ISSUE TITLE
JSON feed

### ISSUE THREAD

**Issue by rmlewisuk** [hexojs/hexo-generator-feed#55]
The [JSON feed spec](https://jsonfeed.org/version/1) was announced yesterday and I am looking to add this to my Hexo site. I'm already using this plugin for RSS and my question is this:

Is this something that'd be useful as part of this plugin (I'm willing to do the work and open a PR) or would it be better for me to fork and create a version specific to JSON feed?

Thanks

**Comment by rmlewisuk** [comment]
Something has just occurred to me though: it's likely that anyone using JSON feed would want it in addition to RSS/Atom so maybe it would be better as a separate plugin.

**Comment by NoahDragon** [comment]
@rmlewisuk agree, better a separate plugin.
