### ISSUE TITLE
安装feed插件，出现模板渲染错误！！！

### ISSUE THREAD

**Issue by huozk0804** [hexojs/hexo-generator-feed#62]
# 描述 
我在安装feed插件之后，在生成文件'hexo g',之后提示我模板渲染错误的问题，这让我无法生成文件。但是我在package.json中删除掉‘"hexo-generator-feed": "^1.2.2",’，之后我再次生成文件则可以正常生成，请问这是什么问题。
# 错误显示
![tim 20180624135903](https://user-images.githubusercontent.com/21075238/41816395-cf925ef4-77b6-11e8-832e-7a217bd2bc6a.png)
# 配置
![tim 20180624140043](https://user-images.githubusercontent.com/21075238/41816396-034eb530-77b7-11e8-98ec-de4a68690767.png)
电脑系统：windows10 ×64
博客主题：next

**Comment by wangdehu** [comment]
是否可以给出更详细的_config.yml 以及确认是否已经执行过npm install  真正安装了hexo-generator-feed

**Comment by SettingDust** [comment]
确实出现问题 config里面没有任何feed相关配置 问题是我升级到hexo3.80出现的 删除掉之后npm i就可以使用了
