### ISSUE TITLE
Domain should not be uri encoded (for IDN) 

### ISSUE THREAD

**Issue by tomap** [hexojs/hexo-generator-feed#63]
Hi,

You should not uri encode the domain. For IDN (international domain names), it produces the wrong result:
https://github.com/hexojs/hexo-generator-feed/blob/master/atom.xml#L8
https://tpî.eu should not be uri encoded into `https://tp%C3%AE.eu/`
You can either leave is like that or use the punycode version `https://xn--tp-rja.eu/` (but I'm not sure you have a function for that and it is not needed)

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-feed/pull/82

**Comment by curbengh** [comment]
hexo-generator-sitemap might have similar issue.
