### ISSUE TITLE
Publish the package

### ISSUE THREAD

**Issue by TitiAlone** [hexojs/hexo-generator-feed#89]
Hello,

I wanted to use the icon customization functionnality, but couldn't because the currently published package on NPM (v1.2.2) is 2 years old, and therefore does not match the master branch at all.

Could somebody publish this pckage so that we can use all the new functionnalities is provides?

**Comment by YoshinoriN** [comment]
Now we are upgrading all of the official plugins. Please wait a while. We will publish new version near future.

Thanks :)
