### ISSUE TITLE
Config to turnoff excerpt in RSS?

### ISSUE THREAD

**Issue by aetherwu** [hexojs/hexo-generator-feed#90]
Sometime I turn on excerpt for index/catalog page for readability, but still want full text output for RSS reader users.

Could you please add a rss config to output full-text in force?

I use excerpt cmd below:

```
<!-- more -->
```

**Comment by tomap** [comment]
Indeed, that seems like a good idea. No need to force the rss user to go to the site.
It should be fairly easy to implement
I'll do a PR if I have time

**Comment by YoshinoriN** [comment]
@aetherwu 
The option already exists and its default value is `true`.  Please check and try to enable `content` option like following.

```yaml
feed:
    content: true
    ...
```

**Comment by aetherwu** [comment]
@YoshinoriN I see. Thank you for notification!
